// <auto-generated />
using System;
using BtgApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BtgApi.Migrations
{
    [DbContext(typeof(BTGDB))]
    partial class BTGDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BtgApi.Models.Aplicacao", b =>
                {
                    b.Property<int>("AplicacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProdutoFinanceiroID")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AplicacaoID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ProdutoFinanceiroID");

                    b.ToTable("Aplicacoes");
                });

            modelBuilder.Entity("BtgApi.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteID = 1,
                            NomeCliente = "Luiz Cliente 1"
                        },
                        new
                        {
                            ClienteID = 2,
                            NomeCliente = "Pedro Cliente 2"
                        },
                        new
                        {
                            ClienteID = 3,
                            NomeCliente = "Joice Cliente 3"
                        });
                });

            modelBuilder.Entity("BtgApi.Models.ProdutoFinanceiro", b =>
                {
                    b.Property<int>("ProdutoFinanceiroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeProdutoFinanceiro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProdutoFinanceiroID");

                    b.ToTable("ProdutosFinanceiros");

                    b.HasData(
                        new
                        {
                            ProdutoFinanceiroID = 1,
                            NomeProdutoFinanceiro = "Certificado de Depósito Bancário"
                        },
                        new
                        {
                            ProdutoFinanceiroID = 2,
                            NomeProdutoFinanceiro = "Fundos de Investimento"
                        },
                        new
                        {
                            ProdutoFinanceiroID = 3,
                            NomeProdutoFinanceiro = "Ações"
                        });
                });

            modelBuilder.Entity("BtgApi.Models.Resgate", b =>
                {
                    b.Property<int>("ResgateID")
                        .HasColumnType("int");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataResgate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ImpostoRenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoFinanceiroID")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorLiquidoIR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorResgate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ResgateID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Resgates");
                });

            modelBuilder.Entity("BtgApi.Models.Aplicacao", b =>
                {
                    b.HasOne("BtgApi.Models.Cliente", "Cliente")
                        .WithMany("ListaAplicacoes")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BtgApi.Models.ProdutoFinanceiro", "ProdutoFinanceiro")
                        .WithMany("ListaAplicacoes")
                        .HasForeignKey("ProdutoFinanceiroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ProdutoFinanceiro");
                });

            modelBuilder.Entity("BtgApi.Models.Resgate", b =>
                {
                    b.HasOne("BtgApi.Models.Cliente", "Cliente")
                        .WithMany("ListaResgates")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BtgApi.Models.ProdutoFinanceiro", "ProdutoFinanceiro")
                        .WithMany("ListaResgates")
                        .HasForeignKey("ResgateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ProdutoFinanceiro");
                });

            modelBuilder.Entity("BtgApi.Models.Cliente", b =>
                {
                    b.Navigation("ListaAplicacoes");

                    b.Navigation("ListaResgates");
                });

            modelBuilder.Entity("BtgApi.Models.ProdutoFinanceiro", b =>
                {
                    b.Navigation("ListaAplicacoes");

                    b.Navigation("ListaResgates");
                });
#pragma warning restore 612, 618
        }
    }
}
