// <auto-generated />
using System;
using BackEndPicPay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndPicPay.Migrations
{
    [DbContext(typeof(PicPayDB))]
    partial class PicPayDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackEndPicPay.Models.Carteira", b =>
                {
                    b.Property<int>("IdCarteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPFcnpj")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SaldoConta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCarteira");

                    b.HasIndex("CPFcnpj", "Email")
                        .IsUnique();

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("BackEndPicPay.Models.Transferencia", b =>
                {
                    b.Property<Guid>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("EnviarId")
                        .HasColumnType("int");

                    b.Property<int>("ReceberId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTransferencia");

                    b.HasIndex("EnviarId");

                    b.HasIndex("ReceberId");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("BackEndPicPay.Models.Transferencia", b =>
                {
                    b.HasOne("BackEndPicPay.Models.Carteira", "Enviar")
                        .WithMany()
                        .HasForeignKey("EnviarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transacao_Enviar");

                    b.HasOne("BackEndPicPay.Models.Carteira", "Receber")
                        .WithMany()
                        .HasForeignKey("ReceberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transacao_Receber");

                    b.Navigation("Enviar");

                    b.Navigation("Receber");
                });
#pragma warning restore 612, 618
        }
    }
}
